### ISSUE TITLE
Error: missing authentication information

### ISSUE THREAD

**Issue by jamesdorfman** [Kixunil/btc-rpc-proxy#16]
Hi. I tried running the proxy using the default `./btc_rpc_proxy.toml`.
The only change I made was to update the Bitcoin RPC username and password.

I ran
```
cargo run --release
```

However, I received the error
```
Error: missing authentication information
```

Is this expected behaviour? It looks like the the config file is not being found....

More specifically, within `src/create_state.rs`, the varaibles `config.bitcoind_user` and `config.bitcoind_password` are both set to `None` in
```
    let auth = AuthSource::from_config(
        config.bitcoind_user,
        config.bitcoind_password,
        config.cookie_file,
    )?;
 ```

Not sure why that might be. As I said, I'm using the default `btc_rpc_proxy.toml` which is provided in the repo.

Thanks for the help!

**Comment by Kixunil** [comment]
Hi, sorry, the auto-loading feature was removed as it was annoying if one has both mainnet and regtest and I forgot to update the README. Just use `cargo run --release -- --conf btc_rpc_proxy.toml` and it should work. Please LMK if it helps.

**Comment by jamesdorfman** [comment]
That worked great. Thanks for the help and for the quick reply!
